databaseChangeLog:
- changeSet:
    id: createTable-routes
    author: saksham
      changes:
      - createTable:
          schemaName: public
          tableName: routes
              columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: created_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: timestamp
                  constraints:
                    nullable: false
              - column:
                  name: flight_id
                  type: varchar
                  constraints:
                    nullable: false
              - column:
                  name: source
                  type: varchar
                  constraints:
                    nullable: false
              - column:
                  name: destination
                  type: varchar
                  constraints:
                    nullable: false
              - column:
                  name: start_time
                  type: varchar
                  constraints:
                    nullable: false
              - column:
                  name: end_time
                  type: varchar
                  constraints:
                    nullable: false
              - column:
                  name: days
                  type: varchar